#dataset: stylegan.dataset.CelebAnPortraitsCached
#dataset: stylegan.dataset.CelebAnPortraits_w_Noise
dataset: stylegan.dataset.Merged_CelebAnPortraits_w_Noise
#dataset: stylegan.dataset.CelebA_w_Noise
#dataset: stylegan.dataset.Portraits_w_Noise
model: stylegan.model.TrainModel
iterator: stylegan.trainer.ListTrainer
art_dir: './artworks/images_align'
balanced_datasets: True

label_size: 3
resolution: 128
