#dataset: stylegan.dataset.CelebAnPortraitsCached
#dataset: stylegan.dataset.CelebAnPortraits_w_Noise
dataset: stylegan.dataset.Merged_CelebAnPortraits_w_Noise
#dataset: stylegan.dataset.CelebA_w_Noise
#dataset: stylegan.dataset.Portraits_w_Noise
model: stylegan.model.TrainModel
iterator: stylegan.trainer.ListTrainer
#wikiart_dir: './wikiart'
art_dir: './artworks/images_align'
balanced_datasets: True

batch_size: 32
num_steps: 1000000

log_freq: 500
ckpt_freq: 10000
ckpt_keep: 1
log_images_to_tensorboard: True

lr: 1.5e-3
lr_decay_begin: 1000000000
lr_decay_end: 1000000001

label_size: 3
#label_size: 1
resolution: 128
#truncation_psi: 1
