#dataset: stylegan.dataset.CelebAnPortraitsCached
dataset: stylegan.dataset.CelebAnPortraits_w_Noise
#dataset: stylegan.dataset.CelebA_w_Noise
model: stylegan.model.TrainModel
iterator: stylegan.trainer.ListTrainer
wikiart_dir: './artworks'

batch_size: 32
num_steps: 1000000

log_freq: 1000
ckpt_freq: 10000
ckpt_keep: 1
log_images_to_tensorboard: True

lr: 1.5e-3
lr_decay_begin : 1000000 # TODO remove these in future versions
lr_decay_end : 10000000  # TODO remove these in future versions

label_size: 2
#label_size: 1
resolution: 128
